### PR TITLE
Add syntax highlighting for codes

### PR DESCRIPTION
**Pull request by Seniru**
Hi! I just created a syntax highlighter for your cute language. It probably contains few bugs. But I'm working on them try to fix them soon.

### CODE REVIEW

**Comment by BirbLanguage** [comment]
Looks awesome so far!
One problem that it seems to be having trouble with is that it's highlighting smaller sections within the text thinking that's its own individual keyword, so I'll definitely look into tweaking that a bit and it should be good to go from there. Thanks for the contribution though!

**Comment by Seniru** [comment]
Yep! I also noticed that and working to fix it

**Comment by Seniru** [comment]
Hi Faisal! I rewrote the highlighter so now it works as we want. Also I managed to reduce the code size and increase it's efficiency.
Here is how the new version looks like.
birb_highlighter

**Review by BirbLanguage — APPROVED** [review]
Great job! It really works well :D

**Comment by Seniru** [comment]
Yeah! Thanks a lot
But with the new changes you have made it is difficult to distinguish strings from conditionals. Can you changed the colors of strings or conditionals

**Pull request merged**
